synapsecns/sanguine

- README.md
The text links to ethereum-optimism repo's good first issue. Updated the README to point to this repo, but it seems like no 'good first issues' are configured.
Should this just link to the issues page as the `/contribute` page on the repo has not been configured yet?
> Fix README Link

- .github/workflows/foundry-tests.yml
Since going open source, the ubuntu-latest-16cores has stopped working (See: #1028), while this requires some further investigation to see if we can fix, we can split up two particularly slow jobs in the mean time
> speedup foundry snapshot a bit

- packages/synapse-interface/components/layouts/LandingPageWrapper/index.tsx
- packages/synapse-interface/constants/routes.ts
- packages/synapse-interface/constants/urls/index.tsx
Removes unsupported link:
27488976f5624900ee3a61e2291210211e0cbc02: [synapse-interface preview link ](https://sanguine-synapse-interface-qz62ggm5s-synapsecns.vercel.app)
> Removes 404ing portfolio link

- packages/synapse-interface/pages/stake/StakeCard.tsx
- packages/synapse-interface/utils/actions/getStakedBalance.ts
Fixes stake page balances not displaying, due to a bug caused from poolId being 0 & `!stakingPoolId` returning true.
> FE: Hotfix - Stake page balances

- services/scribe/node/scribe.go
These don't work and intermittently remove old logs. These should be removed until this is no longer the case.
> disable confirm checks on scribe

- packages/synapse-interface/components/StateManagedBridge/ChainSlideOver.tsx
- packages/synapse-interface/components/StateManagedBridge/TokenSlideOver.tsx
- packages/synapse-interface/store/store.ts
null
6d1e0c598ca6f462c73bb0d8e5dcfc562f0d05e5: [synapse-interface preview link ](https://sanguine-synapse-interface-80gua7x3v-synapsecns.vercel.app)
766cebd253faeff208de9d34a9dc0c7da3db5220: [synapse-interface preview link ](https://sanguine-synapse-interface-h680r3f10-synapsecns.vercel.app)
754f9fc1fa48508600d5842782a96b781fd8b164: [synapse-interface preview link ](https://sanguine-synapse-interface-ci69m3lnl-synapsecns.vercel.app)
> Clears search when exiting slideOver

- services/cctp-relayer/config/config.go
- services/cctp-relayer/config/config_test.go
- services/cctp-relayer/relayer/relayer.go
Use the core backoff library instead of external `backoff` so that the retry can be cancelled when the context is cancelled.
> CCTP relayer backoff respects context

- ethergo/submitter/README.md
- ethergo/submitter/queue.go
- ethergo/submitter/submitter.go
- ethergo/submitter/submitter_test.go
- services/cctp-relayer/go.mod
- services/cctp-relayer/go.sum
As part of #1091, we need to build a better interface for getting the status of transactions for callers to get tx completion data. This will involve the introduction of several new methods to the `TransactionSubmitter` service in future prs.
```go
// GetNonceStatus gets the status of a nonce on a given chain
GetNonceStatus(ctx context.Context, chainID *big.Int, nonce uint64) (status core.NonceStatus, err error)
// GetTXHash gets the tx hash for a given chain and nonce.
GetTXHash(ctx context.Context, chainID *big.Int, nonce uint64) (txHash common.Hash, err error)
```
This should solve the current confirmation queue issue.
> Fix Tx Confirmation Bug

- packages/rest-api/app.ts
- packages/rest-api/package.json
- yarn.lock
Allows the API to return results that have decimal values.
For example, a query to `/bridge?fromChain=1&toChain=42161&fromToken=gOHM&toToken=gOHM&amount=10` would result with `maxAmountOutStr` of 9, when the underlying human-readable value is actually 9.995. After applying this fix we get the expected result of 9.995.
> Fix: allow API to return results with decimals

- packages/explorer-ui/components/misc/ToolTip.tsx
Description
This small edit makes it such that every chain show up upon hovering over the graphs.
4bc3f5c53918f3e3de8cbc2451facf0ae2a6b034: [explorer-ui preview link ](https://sanguine-d05xyvxux-synapsecns.vercel.app)
> allow every chain to show volume even if 0 upon scrolling through graph

- packages/synapse-interface/pages/pool/PoolInfoSection/index.tsx
- Was displaying USD vs. Native Currency total
4d2f388bcbfe44720ad92c7f5e11fcee37f720c2: [synapse-interface preview link ](https://sanguine-synapse-interface-bhai41f09-synapsecns.vercel.app)
> Fixes total locked display

- packages/synapse-interface/constants/tokens/master.tsx
Update USDC name to USD Coin
10a395302a1600bf5c4d3f13bbed1cd899add8d4: [synapse-interface preview link ](https://sanguine-synapse-interface-7e3c94ydv-synapsecns.vercel.app)
> Fix/synapse UI usdc

- packages/synapse-interface/components/Portfolio/SingleNetworkPortfolio.tsx
- packages/synapse-interface/components/layouts/LandingPageWrapper/TopBarNavLink.tsx
- packages/synapse-interface/components/layouts/LandingPageWrapper/index.tsx
- packages/synapse-interface/constants/routes.ts
- Reset Portfolio viewport during Approval flow after users switch network
- Bridge to be highlighted when on Bridge experience in Navbar
789fac488e1f5385af8212d11f58cba9ee70187d: [synapse-interface preview link ](https://sanguine-synapse-interface-8nvtbwwct-synapsecns.vercel.app)
4de0680379580bf5f2fb8f30b42b79021959f69b: [synapse-interface preview link ](https://sanguine-synapse-interface-o35q1s3iq-synapsecns.vercel.app)
6071f36f043b16772d649fc00b152bb4054f24dc: [synapse-interface preview link ](https://sanguine-synapse-interface-kaikb3fus-synapsecns.vercel.app)
> Add scroll after network changes during approval flow

- packages/synapse-interface/constants/routes.ts
- packages/synapse-interface/constants/urls/index.tsx
- packages/synapse-interface/cypress/e2e/navigation.cy.ts
- packages/synapse-interface/cypress/fixtures/navigation.json
Adds back contracts path and links to contracts in docs directly
e3a4d11fdd80182fb0a240f3f6ad7c18ea63761a: [synapse-interface preview link ](https://sanguine-synapse-interface-ep9uy1odj-synapsecns.vercel.app)
ff233686703ba7c971ee08f914cbf078a725e010: [synapse-interface preview link ](https://sanguine-synapse-interface-2iyh3qrbx-synapsecns.vercel.app)
9d1846ad42b1c59342de43edcffbe20daa2e2212: [synapse-interface preview link ](https://sanguine-synapse-interface-n7nzyvdcm-synapsecns.vercel.app)
> Contract path links out directly to contracts in docs

- services/omnirpc/http/client.go
FastHTTP was causing issues with multiple providers that had tepid support for multiplexing. This changes resty to be the default option
> use resty by default

- packages/synapse-interface/constants/tokens/master.tsx
Replaces "DFK_USDC" DFK address w/ NUSD address. Fixes issue of seeing duplicate coins as different entities.
d17488016f2c553e4c4772b5c4986b904f501c13: [synapse-interface preview link ](https://sanguine-synapse-interface-k217f9cet-synapsecns.vercel.app)
dcc42ff46bfc7318d85bd42c864cc9c48d670420: [synapse-interface preview link ](https://sanguine-synapse-interface-490tw1nvr-synapsecns.vercel.app)
> Fixes DFK_USDC/NUSD issue on DFK

- services/explorer/graphql/client/client.go
- services/explorer/graphql/client/queries/queries.graphql
- services/explorer/graphql/server/graph/model/models_gen.go
- services/explorer/graphql/server/graph/queries.resolvers.go
- services/explorer/graphql/server/graph/queryutils.go
- services/explorer/graphql/server/graph/resolver/server.go
- services/explorer/graphql/server/graph/schema/queries.graphql
- services/explorer/graphql/server/graph/schema/types.graphql
Adding new endpoints to explorer for retrieving origin and destination txs for bridgewatcher to
- reduce rpc load on the fe
- provide more reliability
- build off existing services stack
> Explorer Bridgewatcher

- ethergo/submitter/submitter.go
emit a log when the txsubmitter routine exits
> log txsubmitter exit

- packages/sdk-router/src/sdk.ts
- packages/sdk-router/src/utils/deadlines.ts
- Fixed issue with static deadlines produced by the SDK.
- Updated SynapseRouter address on Base to match the default `0x7E7..96a` address
> Fix: sdk deadlines

- packages/sdk-router/src/sdk.test.ts
- packages/sdk-router/src/sdk.ts
- `bridge()` and `bridgeQuote()` functions now throw an error, if equal chain ids were passed for origin and destination chains.
- Added test coverage.
> Fix:sdk same chain ids

- services/cctp-relayer/relayer/relayer.go
This potentially fixes the context leak we attempted to identify in #1995 by checking for context cancellation when we attempt to add to the channel
> [CCTP Relayer] fix context leak

- ethergo/backends/anvil/anvil.go
- ethergo/backends/anvil/client.go
Fixes foundry tag, if this works thanks to https://github.com/foundry-rs/foundry/pull/5414 should pave the path for a built in explorer for foundry backends
I managed to fix this before opening up an issue on foundry, but here's my draft below if useful:
> Since [6e041f9751efa6b75420689b862df05b0934022b](https://github.com/foundry-rs/foundry/commit/6e041f9751efa6b75420689b862df05b0934022b) I've noticed what I think is a regression (and is definitely a behavior change in anvil) with regards to handling of account impersonation and unsigned transaction handling. At commit [7398b65e831f2339d1d0a0bb05ade799e4f9d01e](https://github.com/foundry-rs/foundry/commit/7398b65e831f2339d1d0a0bb05ade799e4f9d01e) (the previous commit, the following sequence was possible:
> 
> <img …
> update foundry tag

- services/omnirpc/cmd/flags.go
Fixes omnirpc bug where `port` set in the config is ignored. This bug was present because the default value for the command line is always set:
and since the command line is prioritized over the config file:
config file is always ignored!
> fix omnirpc port default behavior

- packages/sdk-router/src/sdk.test.ts
- packages/sdk-router/src/sdk.ts
Adds flag to the bridge quoting function allowing to exclude quotes through `SynapseCCTP`. Useful for integrations that only support `SynapseRouter`, and wish to use the latest SDK w/o getting quotes through `SynapseCCTPRouter`.
> SDK: add "exclude cctp" flag to `bridgeQuote`

- core/os.go
- core/os_test.go
> add core copyfile func

- packages/synapse-interface/components/SwapExchangeRateInfo.tsx
- packages/synapse-interface/pages/swap/SwapCard.tsx
- packages/synapse-interface/utils/bigint/format.ts
- Fixes off by 100 error on percentage
- Renames as SwapExchangeRateInfo, deprecates unused code
84e61f837408a6b16465c5d9741744e682038c3c: [synapse-interface preview link ](https://sanguine-synapse-interface-8ggub6kpx-synapsecns.vercel.app)
> Fixes slippage percentage

- packages/sdk-router/src/sdk.test.ts
One of the tests assumed that `SynapseRouter` will be used for Arbitrum -> Optimism transfer, but now SynapseCCTPRouter provides a better quote.
- Error popped up in #1328
> Fix: SDK failing test

- packages/synapse-interface/components/StateManagedBridge/BridgeTransactionButton.tsx
Update Bridge Transaction button state when bridge inputs (chain / token) is updated by user
1ddf77871aa8cce397eea9218966215306f917bc: [synapse-interface preview link ](https://sanguine-synapse-interface-ja7rlkthy-synapsecns.vercel.app)
> Sufficient balance useMemo to update when chain/token updates

- .github/workflows/go.yml
- ethergo/client/client.go
Tracking in: https://github.com/synapsecns/sanguine/pull/1280#issuecomment-1712525480
> Fraud Report Final Touches 🎉

- packages/synapse-interface/codegen.ts
- packages/synapse-interface/slices/api/generated.ts
- yarn.lock
- Fixes failed `Typescript Packages / lint` CI job.
- Added prettier hook so that the generated file is prettified automatically.
476ab05e1ac0419b6eebbb1ac909771ff249ddc7: [synapse-interface preview link ](https://sanguine-synapse-interface-9feqo3ew2-synapsecns.vercel.app)
5b532b69d618cbea23f5bc5337174a66b5decfb7: [synapse-interface preview link ](https://sanguine-synapse-interface-7t8l2t3rr-synapsecns.vercel.app)
> Fix: lint graphql codegen

- .gitmodules
- packages/contracts-core/contracts/create3/CREATE3Factory.sol
- packages/contracts-core/contracts/create3/ICREATE3Factory.sol
- packages/contracts-core/remappings.txt
- packages/contracts-core/script/DeployCREATE3.sol
- packages/contracts-core/script/utils/DeployerUtils.sol
Reverts synapsecns/sanguine#1387
Undoing this for now, when I checked manually to see if #1387 broke anything, I was on the wrong branch
> Revert "Replace Create3 with ZeframLou/create3-factory"

- packages/synapse-interface/constants/chains/master.tsx
> change eth rpc hotfix

- packages/synapse-interface/actions/harvestLpPool.ts
- packages/synapse-interface/actions/stakeLpToken.ts
- packages/synapse-interface/actions/swapPoolAddLiquidity.ts
- packages/synapse-interface/actions/swapPoolRemoveLiquidity.ts
- packages/synapse-interface/actions/swapPoolRemoveLiquidityOneToken.ts
- packages/synapse-interface/actions/unstakeLpToken.ts
- Fixes destructuring issue related to viem/wagmi upgrade. `prepareWriteContract` require a particular format of `const { request } = await prepareWriteContract({...})` where `writeContract` expects its input to be named `request`.
From docs: https://wagmi.sh/core/actions/prepareWriteContract
add67bec5fff5360016610803ff0cd080425ba3d: [synapse-interface preview link ](https://sanguine-synapse-interface-ma0onamvo-synapsecns.vercel.app)
> Fixes destructure typing mismatch on using prepareWriteContract

- charts/agents/Chart.lock
- charts/agents/Chart.yaml
- charts/explorer/Chart.lock
- charts/explorer/Chart.yaml
- charts/omnirpc/Chart.yaml
- charts/omnirpc/values.yaml
- charts/scribe/Chart.lock
- charts/scribe/Chart.yaml
- charts/scribe/templates/configmap.yaml
Allows us to use templating to clean up helm charts for scribe deployments.
> Add templating to scribe configmap

- packages/synapse-interface/utils/actions/getPoolData.ts
**Currency Reserves** component on the pool page is currently using treating pool's token balances as the available reserves, when in fact this number includes the unclaimed admin fees. Pool's ABI exposes a separate function `getTokenBalance`, which is used to get the pool's reserves in this PR.
`getBalanceData` is used both for retrieving pool's internal balances, as well as user's balances of pool's tokens, so the logic was slightly adjusted to accommodate this flow.
1ee2a66b965b5b3346c1b61f7806fab9fe2ed13c: [synapse-interface preview link ](https://sanguine-synapse-interface-92b7ifedn-synapsecns.vercel.app)
194fe693478f123e528060e609c439a34bc9e78c: [synapse-interface preview link ](https://sanguine-synapse-interface-dru1jowzg-synapsecns.vercel.app) …
> Fix: exclude unclaimed admin fees from pool's displayed reserves

- packages/explorer-ui/constants/tokens/basic.ts
- packages/synapse-interface/constants/tokens/bridgeable.ts
null
b8ba8d7c7f5a161b4d3d745642a58fb2a52a7539: [synapse-interface preview link ](https://sanguine-synapse-interface-4rjjtk2ql-synapsecns.vercel.app)
827629daca42cb9373dee93390227846796e4790: [explorer-ui preview link ](https://sanguine-8s167f5qs-synapsecns.vercel.app)
827629daca42cb9373dee93390227846796e4790: [synapse-interface preview link ](https://sanguine-synapse-interface-mfmq0e04h-synapsecns.vercel.app)
> Typo fix, rename to Liquity

- packages/synapse-interface/components/StateManagedBridge/BridgeExchangeRateInfo.tsx
null
ec3787a99613dd6e23806300a169a29e16d21246: [synapse-interface preview link ](https://sanguine-synapse-interface-7yskdv5bs-synapsecns.vercel.app)
> Fixes gasdrop to null when toChain is Eth

- packages/synapse-interface/components/StateManagedBridge/BridgeTransactionButton.tsx
- packages/synapse-interface/constants/chains/index.tsx
Resume Harmony
3765f57e7f99a74265448a7d3a793b076c595555: [synapse-interface preview link ](https://sanguine-synapse-interface-qz3pr1d2i-synapsecns.vercel.app)
> Unpause harmony

- services/rfq/relayer/reldb/base/model.go
- services/rfq/relayer/reldb/base/quote.go
- services/rfq/relayer/reldb/db.go
- services/rfq/relayer/service/handlers.go
Add the `DestTxHash` field to `QuoteRequest` and `RequestForQuote` models, and set this field when `RelayComplete` status is set.
> Add `DestTxHash` field and use it in relayer `Prove()` call

- services/rfq/api/client/client.go
- services/rfq/relayer/quoter/quoter.go
Gets the appropriate `OriginFastBridgeAddress` and `DestFastBridgeAddress` from the relayer config and includes them in the quoter API response.
> Add contract addresses to quoter API response

- packages/contracts-rfq/contracts/FastBridge.sol
- packages/contracts-rfq/contracts/interfaces/IFastBridge.sol
- packages/contracts-rfq/test/FastBridge.t.sol
- packages/contracts-rfq/test/FastBridgeMock.sol
Removes `address to` param from `FastBridge.sol::refund`
**Metadata**
> `refund` to originSender only

- services/stiprelayer/db/sql/base/store.go
- services/stiprelayer/db/stip_db.go
- services/stiprelayer/relayer/relayer.go
- services/stiprelayer/stipapi/server.go
- services/stiprelayer/stipconfig/config.go
Adds a cap of ARB per address in the STIP relayer. This is done by querying all STIP transactions for a given address and summing the `arb_amount_rebated` field.
Note that the default cap is set to 2000 ARB, but config value will override.
> Add ARB cap per address in STIP relayer

- packages/contracts-communication/contracts/interfaces/IExecutionFees.sol
- packages/contracts-communication/contracts/interfaces/IExecutor.sol
> Interfaces for execution

- packages/contracts-communication/contracts/InterchainClientV1.sol
- packages/contracts-communication/contracts/interfaces/IInterchainApp.sol
- packages/contracts-communication/contracts/libs/AppConfig.sol
- packages/contracts-communication/foundry.toml
- packages/contracts-communication/test/InterchainClientV1Test.t.sol
- packages/contracts-communication/test/harnesses/AppConfigLibHarness.sol
- packages/contracts-communication/test/libs/AppConfigLib.t.sol
- packages/contracts-communication/test/mocks/InterchainAppMock.sol
Adds a library to deal with versioned app configs.
**Note**
`InterchainApp.sol` isn't currently implementing `IInterchainApp`, which will be fixed in a separate PR.
> Add `AppConfig` library

- packages/synapse-interface/components/StateManagedBridge/BridgeExchangeRateInfo.tsx
Show both rebate versions in Bridge Card
a5835069174d070a387c610b6e6a4e29b6be7c0f: [synapse-interface preview link ](https://sanguine-synapse-interface-kk8jc78a0-synapsecns.vercel.app)
> feat(synapse-interface): use both rebate displays in bridge card

- packages/synapse-interface/components/StateManagedBridge/BridgeExchangeRateInfo.tsx
Use bridge rebate display (one on same line as time estimate) in favor of displaying within Bridge Receipt
f1be8fddd852affe3b11dc26f1ee4ec31d884de3: [synapse-interface preview link ](https://sanguine-synapse-interface-p8hxdxdp5-synapsecns.vercel.app)
> feat(synapse-interface): switch to previous rebate version

- .github/workflows/go.yml
Supercedes #2333, master should be merged into communication after this at some point to fix this issue
Context: on #2234 and child branches golangci-lint has been failing. This [comment](https://github.com/golangci/golangci-lint/discussions/1920#discussioncomment-8664443) hints this was a result of old go version.
We were stopped from updating this because of golangci/golangci-lint#3420 (see regression in: #534/#532), but that was fixed w/ the upgrade in #2204.
> fix golangci-lint

- .gitmodules
- packages/contracts-communication/foundry.toml
- packages/contracts-communication/package.json
- packages/contracts-communication/remappings.txt
This PR removes the submodules from new package `contracts-communication` entirely and uses the npm packages instead.
- `forge-std` and its internal `ds-test` submodules are replaced by the dependencies of `solidity-devops` https://github.com/synapsecns/sanguine/blob/3cc1c5244184a9c5b71a77341f56f58f6f99269f/packages/solidity-devops/package.json#L32-L33
- `openzeppelin-contracts` is replaced by the corresponsing dependency, pinning the version to `5.0.1`
Updated the remappings to make sure everything is working as expected.
I suggest merging this into `feat/communication` when there are no opened PRs into that branch, so that the submodules are removed for good in the newer branches w/o any conflicts.
> Remove submodules from `contracts-communication`

- contrib/promexporter/config/config.go
> add new addresses to promexporter

- packages/sdk-router/src/constants/medianTime.ts
> SDK Base RFQ Time

- ethergo/submitter/db/txdb/store.go
Temporarily lower `MaxResultsPerChain` from 50 to 1 to increase resiliency upon submission
> Submitter: lower batch size from 50 to 1

- services/rfq/relayer/inventory/synapse.go
Fix error marshalling in rfq rebalancer
> fix rfq error marshalling

- packages/solidity-devops/package.json
Skips tag that was mistakenly created and overriden a while ago:
- https://github.com/synapsecns/sanguine/releases/tag/%40synapsecns%2Fsolidity-devops%400.2.0
> fix(solidity-devops): skip 0.2.0

- packages/solidity-devops/js/utils/chain.js
Temp fix to prevent sending txs with `maxGasFee = maxPriority`, like this one:
- https://sepolia.etherscan.io/tx/0xf8dc43c60ce79d213bd07ba9d615d6030c6345a5a24d8562f1b914b10330047d
- Caused by https://github.com/foundry-rs/foundry/issues/7486
> fix(solidity-devops): set only priority fee until foundry bug is fixed

- .github/workflows/solidity.yml
> Fix solidity CI workflow in `contracts-communication`

- .github/workflows/go.yml
- .github/workflows/goreleaser-actions.yml
> wrap workflow

- packages/synapse-interface/pages/state-managed-bridge/index.tsx
- packages/synapse-interface/utils/hooks/useStaleQuoteUpdater.ts
Updater now only fires a single callback regardless of how many `staleTimeout` intervals were passed since User has not moved mouse. Prevents multiple callbacks from being fired off if User has not been active in window for an extended period of time. 
fc79d27fb8de1668ddd5d34c8ce749d994b32249: [synapse-interface preview link ](https://sanguine-synapse-interface-419b8stz6-synapsecns.vercel.app)
> feat(synapse-interface): optimize stale quote updater

- packages/synapse-constants/constants/chains/master.ts
changes the route from etherscan.com to etherscan.io. Changes it in the constants npm package.
> updating etherscan link in explorer-ui

- .github/workflows/go.yml
- .github/workflows/goreleaser-actions.yml
- core/README.md
- docker/goreleaser/Dockerfile
- services/rfq/guard/service/handlers.go
Reverts synapsecns/sanguine#2891
> revert namespace integration

- packages/synapse-interface/constants/bridgeMap.ts
- packages/synapse-interface/scripts/abi/FastBridgeRouter.json
- packages/synapse-interface/scripts/generateMaps.js
- packages/synapse-interface/scripts/utils/fetchRfqData.js
- Simplified the generation of the bridge maps for RFQ by making it a bit more generic. 
- Origin liquidity pools are now checked for swap+RFQ type of interactions. 
- The "swappable" lists are now filled for all chains (previously was only filled for chains with SynapseBridge).
- Quotes older than 1 day ago are no longer used to create the RFQ bridge map
c54a3d91b21a7f72f7f5828878db1ee1c56ff073: [synapse-interface preview link ](https://sanguine-synapse-interface-5z3v7h8d8-synapsecns.vercel.app)
> fix(synapse-interface): use rfq origin pools when generating bridge maps

- packages/synapse-interface/messages/fr.json
in the french crypto community, people use "bridge" instead of the direct translation "pont"
21bda4705632fbf9a4ed027c5366c65e7806641e: [synapse-interface preview link ](https://sanguine-synapse-interface-chomgzsr2-synapsecns.vercel.app)
> Update french translation

- docs/bridge/docusaurus.config.ts
- changes the message at the top of the docs
- removes the word "bridge" from the title
35d095670a350b12cc5acc5cc986059a5d4f19f5: [docs preview link ](https://bridge-docs-5psv6sjpt-synapsecns.vercel.app)
> Nits to the new docs

- packages/contracts-rfq/contracts/FastBridge.sol
- packages/contracts-rfq/test/FastBridge.MulticallTarget.t.sol
- packages/contracts-rfq/test/integration/FastBridge.MulticallTarget.t.sol
- packages/contracts-rfq/test/integration/MulticallTarget.t.sol
> feat(contracts-rfq): FastBridge v1 multicall [SLT-324]

- core/ginhelper/server.go
- services/omnirpc/cmd/cmd.go
> optionally disable cors

- packages/contracts-rfq/test/integration/FastBridgeV2.MulticallTarget.t.sol
> test(contracts-rfq): adjust setup to #3336 changes
