.github/workflows/devcontainer.yml
.github/workflows/goreleaser-actions.yml
.github/workflows/jaeger-ui.yml
contrib/git-changes-action/README.md

Fixes goreleaser permissions (See #1024 )

fix goreleaser

---

.github/workflows/goreleaser-actions.yml
contrib/git-changes-action/README.md

Fixes regression made when fixing #1024 wrt content publishing/tag creation

fix content permissions regressed in #1025

---

.github/workflows/ui-preview.yaml

Fixes ui preview vector when output contains no values

fix ui-preview worfklow when matrix vector contains no values

---

packages/synapse-interface/constants/chains/master.tsx

Change Arb RPC

---

packages/synapse-interface/package.json
packages/synapse-interface/pages/index.tsx
yarn.lock

e8b3b7a86112c2ad244b70a98c6cfa17f9c8c38c: [synapse-interface preview link ](https://sanguine-synapse-interface-ia500444u-synapsecns.vercel.app)

Fixes Vercel build on sdk-router versioning issue

---

packages/synapse-interface/components/input/TokenAmountInput/index.tsx

…t clear that it's not bridgeable
**Metadata**
02c4ab6d75e8a11914b2d85d92ffe59abfc2b563: [synapse-interface preview link ](https://sanguine-synapse-interface-a61diphsi-synapsecns.vercel.app)

FE: Zero amount on destination input should stay placeholder text

---

agents/testutil/simulated_backends_suite.go
agents/testutil/suite_test.go
contrib/release-copier-action/go.mod
contrib/release-copier-action/go.sum
core/testsuite/suite.go
services/explorer/go.mod
services/explorer/go.sum
services/omnirpc/go.mod
services/omnirpc/go.sum

Removing dependency from core to ethergo since ehtergo depends on core

Removing dependency from core to ethergo since ethergo depends on core

---

packages/synapse-interface/constants/tokens/master.tsx

**Metadata**
5607a3ad4e6865674995398210d9f491c56eac9f: [synapse-interface preview link ](https://sanguine-synapse-interface-gik6u367s-synapsecns.vercel.app)
490a268086f4f15c8d7940ab4b9fc2043ba17d27: [synapse-interface preview link ](https://sanguine-synapse-interface-k2l2kmca4-synapsecns.vercel.app)
b8e5a7f2c14895eeac4315e1241714f3ccfa2549: [synapse-interface preview link ](https://sanguine-synapse-interface-h2xxqbww4-synapsecns.vercel.app)

Hotfix: Add Klaytn JEWEL address

---

agents/agents/executor/db/datastore/sql/base/base_store.go
agents/agents/executor/db/datastore/sql/base/base_store_test.go
agents/agents/executor/db/datastore/sql/base/crosstable.go
agents/agents/executor/db/datastore/sql/base/logger.go
agents/agents/executor/db/datastore/sql/mysql/store.go
agents/agents/executor/db/datastore/sql/sqlite/store.go

Suggested changes for #987. There's a full explanation in a review comment there [here](https://github.com/synapsecns/sanguine/pull/987#discussion_r1230701791)

[executor] more concise model name getter for #987

---

packages/synapse-interface/components/input/TokenAmountInput/index.tsx

- Add back Mobile max button for bridge/swap
a997c22b13015c7a3ed42099e14caa73d77bc8d7: [synapse-interface preview link ](https://sanguine-synapse-interface-lclchfuqu-synapsecns.vercel.app)

Feat/synapse UI bridge mobile max

---

packages/sdk-router/src/synapseRouter.ts

yarn & sdk

---

packages/sdk-router/src/synapseRouter.ts
packages/synapse-interface/package.json

FE sdk v201

---

packages/synapse-interface/package.json
packages/synapse-interface/store/store.ts
yarn.lock

**Metadata**
14c9fab2abc9f6b16c21337a80d89c890d11a089: [synapse-interface preview link ](https://sanguine-synapse-interface-e8h2w8sjz-synapsecns.vercel.app)
48a2c52ea17e258d7d74aede3eb60302c8d65a37: [synapse-interface preview link ](https://sanguine-synapse-interface-ovim5nec8-synapsecns.vercel.app)

test fe deploy

---

packages/sdk-router/src/SynapseCCTPRouter.test.ts
packages/sdk-router/src/sdk.ts
packages/sdk-router/src/synapseRouter.ts
packages/synapse-interface/store/store.ts

There was a ts lint error in store.ts. This PR fixes it.
111885caab91bdc11d1ad0d614923b62858655ae: [synapse-interface preview link ](https://sanguine-synapse-interface-c5dq1n1t9-synapsecns.vercel.app)
29a6d4ddf187922e1727369f6d4313557661c7e1: [synapse-interface preview link ](https://sanguine-synapse-interface-67yre8t2r-synapsecns.vercel.app)
2f17015c0fa3d43320d318b30401e669c2d237b2: [synapse-interface preview link ](https://sanguine-synapse-interface-bnbgl5sqi-synapsecns.vercel.app)
8fd5b22a95f8db9c3cdf2908b42192155dc5619c: [synapse-interface preview link ](https://sanguine-synapse-interface-h4pojdn3s-synapsecns.vercel.app)

Fix ts-lint

---

.github/workflows/sonar.yml
sonar-project.properties

fix properties

---

packages/synapse-interface/package.json
packages/synapse-interface/pages/state-managed-bridge/index.tsx

null
679a60379d5cd798e73a6bcd685bf11825dbe70b: [synapse-interface preview link ](https://sanguine-synapse-interface-jx5az1lyt-synapsecns.vercel.app)

Adds toasts

---

packages/sdk-router/src/sdk.ts

Fix SDK quote for nonCCTP chains

---

packages/synapse-interface/package.json

bump sdk version

---

packages/synapse-interface/pages/state-managed-bridge/index.tsx

null
fb98b3e19244733979a62b36e7a17a03552349a0: [synapse-interface preview link ](https://sanguine-synapse-interface-nhpfcd51d-synapsecns.vercel.app)

Supports pending state for approving tx

---

packages/synapse-interface/components/buttons/SwitchButton.tsx

null
7da0f3951c17fba4ac5f91809ff29db83bf81ef6: [synapse-interface preview link ](https://sanguine-synapse-interface-l5170r6kr-synapsecns.vercel.app)

Slows down switch animation

---

packages/synapse-interface/constants/extraWagmiChains.ts
packages/synapse-interface/constants/tokens/master.tsx
packages/synapse-interface/package.json
packages/synapse-interface/pages/_app.tsx

null
2469ff04d5022ac5cc51e550120e8e0f34b7b396: [synapse-interface preview link ](https://sanguine-synapse-interface-15s8def6f-synapsecns.vercel.app)

Adds multicall data to support token balance queries on extra networks

---

.github/workflows/go.yml
.github/workflows/goreleaser-actions.yml
.github/workflows/helm-test.yml
.github/workflows/ui-preview.yaml

Never fail fast in the gh strategy matrix

strategy matrix fix 

---

packages/synapse-interface/pages/bridge/BridgeWatcher/DestinationTx.tsx

**Metadata**
0bbe4991e8e8b139b9aaf439f65f297fb39db365: [synapse-interface preview link ](https://sanguine-synapse-interface-3719ljw8z-synapsecns.vercel.app)

fix typo for build

---

contrib/git-changes-action/README.md

Add diagrams to git-changes-action docs

improve git change docs

---

packages/synapse-interface/components/StateManagedBridge/InputContainer.tsx
packages/synapse-interface/constants/bridge.ts
packages/synapse-interface/utils/bridgeWatcher.ts

null
f247b9a402f2b502fefcc3b1c3a7c4bea5de18c6: [synapse-interface preview link ](https://sanguine-synapse-interface-iqvzx0na2-synapsecns.vercel.app)

Clears input value after successful bridge transaction

---

charts/agents/Chart.lock
charts/agents/Chart.yaml
charts/scribe/Chart.yaml
charts/scribe/templates/indexer_deployment.yaml
charts/scribe/templates/server_deployment.yaml
charts/scribe/values.yaml

Set resources per deployment for scribe

Updated scribe helm chart

---

.github/workflows/goreleaser-actions.yml
CODEOWNERS
agents/README.md
contrib/git-changes-action/README.md
contrib/release-copier-action/README.md
contrib/terraform-provider-helmproxy/readme.md
contrib/terraform-provider-iap/README.md
contrib/terraform-provider-kubeproxy/README.md
contrib/tfcore/README.md
contrib/tfcore/READMe.md
core/README.md
docker/agents.Dockerfile
docker/explorer.Dockerfile
docker/git-changes-action.Dockerfile
docker/goreleaser/Dockerfile
docker/jaeger-ui/Dockerfile
docker/omnirpc.Dockerfile
docker/release-copier-action.Dockerfile
docker/scribe.Dockerfile
ethergo/README.md
services/cctp-relayer/README.md
services/explorer/README.md
services/omnirpc/README.md
services/scribe/cmd/cmd.md
tools/README.md

Fixes some image description bugs

fix docker image description bug

---

packages/synapse-interface/pages/state-managed-bridge/index.tsx

reduce toast duration from 4000ms to 2000ms

toast duration

---

packages/synapse-interface/components/Warning.tsx
packages/synapse-interface/constants/chains/index.tsx
packages/synapse-interface/constants/impairedChains.tsx
packages/synapse-interface/pages/state-managed-bridge/index.tsx

MVP Warning Handler for USDCe / USDC issues on ETH/Arbitrum/Avalanche
984e2df6e1f9cd9b6d24665b3db8c3523e2faf11: [synapse-interface preview link ](https://sanguine-synapse-interface-46c0ns2fh-synapsecns.vercel.app)
eeaf7a59baf2c99a6b33932a38421a6b38807597: [synapse-interface preview link ](https://sanguine-synapse-interface-qu07oi42p-synapsecns.vercel.app)
d71ff2f8b7a26a1d2b6726277e55da87b24fca47: [synapse-interface preview link ](https://sanguine-synapse-interface-4dm7v70c9-synapsecns.vercel.app)
6b6c3da4ddc500318b391a1fb876b50e18781e02: [synapse-interface preview link ](https://sanguine-synapse-interface-g006ebdmo-synapsecns.vercel.app)
fff3dbfe162d009dc05fedb20b63b83bae2a5dcb: [synapse-interface preview link ](https://sanguine-synapse-interface-bfckh2d36-synapsecns.vercel.app) …

Feat/synapse UI warning handler

---

packages/synapse-interface/pages/_document.tsx

Add Document Title for webapp
12102528d8ae9114b47f78141c28ccac87d873d8: [synapse-interface preview link ](https://sanguine-synapse-interface-mx0ekwn7y-synapsecns.vercel.app)
a7595ba2b7fa79eec7378ad7f5603538fa407e67: [synapse-interface preview link ](https://sanguine-synapse-interface-m1mm2xctm-synapsecns.vercel.app)

Add document title

---

packages/synapse-interface/pages/state-managed-bridge/index.tsx

Remove prior Bridge quote toast before showing new
15843581829dbb96005c0784f33e4a1e45fa7ab2: [synapse-interface preview link ](https://sanguine-synapse-interface-gxpkwkpno-synapsecns.vercel.app)

Remove prior toast before showing new

---

packages/synapse-interface/components/StateManagedBridge/InputContainer.tsx
packages/synapse-interface/pages/state-managed-bridge/index.tsx

null
5ec4775524ab1706a13b27502d86a20ca0a9574a: [synapse-interface preview link ](https://sanguine-synapse-interface-6mgq1eonb-synapsecns.vercel.app)

Cleans input for non numbers, fixes decimals input issue

---

packages/synapse-interface/pages/state-managed-bridge/index.tsx

null
9b7ad11dac7a225c986529ad50c0162cb53208e5: [synapse-interface preview link ](https://sanguine-synapse-interface-6cztqxrdq-synapsecns.vercel.app)

Fixes sending msg value for Bigint

---

packages/synapse-interface/constants/tokens/master.tsx

pause USDB

---

packages/synapse-interface/constants/tokens/index.tsx
packages/synapse-interface/constants/tokens/master.tsx

- adds new UNIDX addresses
- unpauses UNIDX
- uncomments out USDB bc it was breaking build in bridgewatcher (remains paused, however)
ec8aa13d3dae86cbf3b009795fb7b5a28fec35f8: [synapse-interface preview link ](https://sanguine-synapse-interface-ehtbvuvbi-synapsecns.vercel.app)

Updates UNIDX

---

services/cctp-relayer/db/sql/base/base.go
services/cctp-relayer/go.mod
services/cctp-relayer/go.sum
services/cctp-relayer/main.go

Clear go-gen on master for cctp relayer

---

packages/synapse-interface/components/Portfolio/Portfolio.tsx
packages/synapse-interface/components/Portfolio/PortfolioTokenAsset.tsx
packages/synapse-interface/components/StateManagedBridge/BridgeTransactionButton.tsx
packages/synapse-interface/components/StateManagedBridge/InputContainer.tsx
packages/synapse-interface/pages/bridge/BridgeWatcher/DestinationTx.tsx
packages/synapse-interface/pages/state-managed-bridge/index.tsx
packages/synapse-interface/slices/bridgeSlice.ts
packages/synapse-interface/store/store.ts
packages/synapse-interface/utils/hooks/usePortfolioBalances.tsx
yarn.lock

- Remove BigNumber / BigInt conversions for `fromValue` in bridge slice
- Fix SynapseCCTP contract undefined error 
- Add scroll to bridge card when clicking 'Amount' column in Portfolio
cc87896e3991d78c4a959cb89134779cfb4777bd: [synapse-interface preview link ](https://sanguine-synapse-interface-qzks18pfm-synapsecns.vercel.app)
add30c7d91521adff59e7c8a64f7d0b0a2be37fc: [synapse-interface preview link ](https://sanguine-synapse-interface-esy6uo7cw-synapsecns.vercel.app)
b047f3bd829286963fc54716a6a03d33d8ac8f00: [synapse-interface preview link ](https://sanguine-synapse-interface-dwu006piw-synapsecns.vercel.app)
a8df0df25427184e4cc5442b3ba4f4c2e4581328: [synapse-interface preview link ](https://sanguine-synapse-interface-e83uyrau2-synapsecns.vercel.app) …

Update middleware to remain as string, remove conversions

---

packages/synapse-interface/components/ApyTooltip.tsx
packages/synapse-interface/utils/bigint/format.ts

null
df3514ae8bb9375ceac066a4b3fb6a4273df5546: [synapse-interface preview link ](https://sanguine-synapse-interface-9tbkohhq0-synapsecns.vercel.app)

Adds try catch on bigint formatters, fixes decimal issue on apy tooltip

---

.github/workflows/go.yml
agents/go.mod
agents/go.sum
core/go.mod
core/go.sum
core/metrics/base.go
core/metrics/noopexporter.go
core/metrics/noopexporter_test.go
ethergo/backends/mocks/simulated_test_backend.go
ethergo/chain/mocks/chain.go
ethergo/go.mod
ethergo/go.sum
services/cctp-relayer/go.mod
services/cctp-relayer/go.sum
services/explorer/go.mod
services/explorer/go.sum
services/omnirpc/go.mod
services/omnirpc/go.sum
services/scribe/api/suite_test.go
services/scribe/go.mod
services/scribe/go.sum
services/scribe/grpc/client/rest/api_scribe_service.go

Update metrics exporter
[afef230](https://github.com/synapsecns/sanguine/pull/1161/commits/afef230001a6248903d9605412acc031f1ba659d) in prod

metric logging  hotfix

---

services/explorer/graphql/server/graph/partials.go
services/explorer/graphql/server/graph/queryutils.go

Fixing daily chain query for fee + bridge view.
Already in prod

Update explorer server

---

tools/.goreleaser.yml
tools/revertresolver/README.md
tools/revertresolver/main.go

Adds a tool to parse custom error types from revert calldata; see README

Add revert resolver tool

---

contrib/promexporter/exporters/exporter.go
core/ginhelper/server.go

simplify metrics endpoint

---

contrib/release-copier-action/copier/copier.go

Fix the temporary directory creation

[release copier] fix tempdir creation

---

README.md
contrib/promexporter/README.md
contrib/promexporter/config/config.go
contrib/promexporter/dashboards/bridges.json
contrib/promexporter/exporters/exporter.go
contrib/promexporter/go.mod
core/metrics/consistentnames.go
services/explorer/api/server.go
services/explorer/db/consumerinterface.go
services/explorer/db/mocks/consumer_db.go
services/explorer/db/sql/reader.go
services/explorer/go.mod

Prom Exporter Updates

---

core/ginhelper/server.go
core/metrics/README.md
core/metrics/base.go
core/os.go
core/os_test.go
ethergo/go.mod
ethergo/go.sum

Adds a metrics port to the metrics configuration

add metrics port

---

.github/actions/setup-nodejs/action.yml

fix yarn cache path

---

packages/sdk-router/README.md

republish api

---

packages/synapse-interface/constants/tokens/master.tsx

allow nETH swaps on Base

---

packages/synapse-interface/constants/tokens/master.tsx
packages/synapse-interface/constants/tokens/swapMaster.ts

ETH -> nETH Swaps base

---

.github/labeler.yml

add label for codeowners changes

---

packages/synapse-interface/actions/swapPoolCalculateAddLiquidity.ts
packages/synapse-interface/constants/bridge.ts
packages/synapse-interface/constants/tokens/swapMaster.ts

**Metadata**
10121abeac11da56a95b9b68e31642f27f622cc0: [synapse-interface preview link ](https://sanguine-synapse-interface-5tvwmqsa8-synapsecns.vercel.app)
525c4b5d8a99b4702d24feb366638602530e56dc: [synapse-interface preview link ](https://sanguine-synapse-interface-9mg5153qt-synapsecns.vercel.app)

Adjust base router and add bridgewatcher base block confs

---

packages/synapse-interface/constants/bridge.ts

base new router sdk rebuild

---

packages/synapse-interface/pages/stake/StakeCard.tsx

Fix lag for Stake Card input
e2c7960d35fd85762c69dbe489feac3d003d179d: [synapse-interface preview link ](https://sanguine-synapse-interface-a7q08awmn-synapsecns.vercel.app)

Fix Stake Card Input Lag

---

packages/explorer-ui/.nvmrc
packages/explorer-ui/README.md
packages/sdk-router/tsconfig.json

Check explorer build status
9aca298747f76aaaed8c9fe372706099579d1fb7: [explorer-ui preview link ](https://sanguine-70urnpzed-synapsecns.vercel.app)

explorer deploy fix

---

packages/synapse-interface/constants/chains/master.tsx

base rpc change

---

services/explorer/config.yaml
services/explorer/consumer/parser/cctpparser.go

Removing cctp prefix from bridge event table kappas.
**Status**
18be702f5067400fa803a2bf44cb0aea4962cc0e in prod

Remove CCTP prefix from bridge kappas

---

packages/synapse-interface/constants/chains/master.tsx

update opti rpc

---

packages/contracts-core/script/utils/DeployerUtils.sol

Error for prediction if create3 not deployed

---

services/cctp-relayer/go.sum

cleanup relayer go.sum

---

ethergo/backends/anvil/anvil.go
ethergo/backends/anvil/options.go
ethergo/backends/anvil/suite_test.go

Otterscan explorer implementation

Add Otterscan to anvil driver

---

packages/synapse-interface/components/StateManagedBridge/BridgeTransactionButton.tsx

null
67155aebf084632f958c468df157b8988a9af1ce: [synapse-interface preview link ](https://sanguine-synapse-interface-4l7h9tvic-synapsecns.vercel.app)

Checks if balance is enough on bridge txn button

---

.github/workflows/go.yml
.github/workflows/sonar.yml
agents/agents/agentsintegration/agentsintegration_test.go
agents/testutil/simulated_backends_suite.go
core/README.md
core/metrics/localmetrics/local.go
core/metrics/metrics_test.go
ethergo/backends/anvil/anvil.go
ethergo/backends/anvil/options.go

See: https://medium.com/@xcoulon/how-to-avoid-parallel-execution-of-tests-in-golang-763d32d88eec
Trying to fix #1280

Second attempt at fixing agents flakes

---

packages/synapse-interface/components/toast/ToastContent.tsx
packages/synapse-interface/utils/txErrorHandler.tsx

null
11917ecb91b26692cac2dcfee5a288d3146c8771: [synapse-interface preview link ](https://sanguine-synapse-interface-e3ai01n1k-synapsecns.vercel.app)

Fix toast error msg when user rejects request from wallet

---

packages/synapse-interface/utils/bigint/format.ts

null
ab526298066015224ce2f7677e73a8710e1182a2: [synapse-interface preview link ](https://sanguine-synapse-interface-n96u10ttp-synapsecns.vercel.app)

Adds check for rawVal existence

---

.github/workflows/goreleaser-actions.yml
agents/README.md

reduce superflous ci runs 

---

agents/agents/guard/cmd/commands.go
agents/agents/notary/cmd/commands.go

add debug flag

---

agents/agents/executor/cmd/commands.go

change to embedded scribe rpc url

---

agents/agents/executor/executor_test.go
agents/agents/notary/notary.go
agents/go.mod
agents/go.sum
agents/testutil/simulated_backends_suite.go

Make the notary use states that originate from the Notary's domain.

Notary Fix Origin State

---

contrib/promexporter/config/config.go

Upadtes the promexporter config

update promexporter config

---

packages/sdk-router/src/constants/index.ts

SDK: Add optimism CCTP

---

packages/synapse-interface/contexts/SegmentAnalyticsProvider.tsx

null
0338bfff9c5d9593462468813b8cb561e19e3d66: [synapse-interface preview link ](https://sanguine-synapse-interface-83462dlri-synapsecns.vercel.app)

Removes address from Segment event title

---

packages/synapse-interface/utils/actions/approveAndDeposit.tsx
packages/synapse-interface/utils/getSwapDepositContractFields.ts

null
5ee3980a3889d65a35c0a4883659420e7aa0db63: [synapse-interface preview link ](https://sanguine-synapse-interface-2511s2c3s-synapsecns.vercel.app)

Fixes pool deposits on Avalanche

---

packages/synapse-interface/constants/tokens/poolMaster.ts

null
68feaf78145847f57733feeb170a979242c0f558: [synapse-interface preview link ](https://sanguine-synapse-interface-ojgew86oy-synapsecns.vercel.app)

Metis USDC

---

packages/synapse-interface/constants/tokens/auxilliary.ts
packages/synapse-interface/constants/tokens/poolMaster.ts

null
f61f054b90683bc3aab5792bd8bfbc803d4092bf: [synapse-interface preview link ](https://sanguine-synapse-interface-gpbdk9iql-synapsecns.vercel.app)

Maps pool tokens to correct addresses

---

packages/synapse-interface/constants/tokens/poolMaster.ts

null
7aace892273bf60273c90906629bb72a06b7208e: [synapse-interface preview link ](https://sanguine-synapse-interface-lrokd0nh7-synapsecns.vercel.app)

Deprecate pool

---

packages/synapse-interface/constants/tokens/poolMaster.ts

null
bd31e55c40aabab2a45b49ba865ca46ca0189354: [synapse-interface preview link ](https://sanguine-synapse-interface-gufzgluqg-synapsecns.vercel.app)

Fixes Harmony stable pool token import

---

packages/synapse-interface/components/StateManagedBridge/ConnectionIndicators.tsx

null
23f351462f591c2135a47f77d4718a502a71ce85: [synapse-interface preview link ](https://sanguine-synapse-interface-7hpsz2knr-synapsecns.vercel.app)

Renames Connect to Switch Network

---

packages/synapse-interface/constants/tokens/poolMaster.ts

null
086203a23ca3173c7be31e2c36e804ca394268f7: [synapse-interface preview link ](https://sanguine-synapse-interface-pyjbdjmhx-synapsecns.vercel.app)

Adds back USDT to Klaytn pool

---

packages/synapse-interface/constants/tokens/bridgeable.ts

null
4cd2d1c94651d02385eed3a7d22ab33711197fae: [synapse-interface preview link ](https://sanguine-synapse-interface-6hu61vjwz-synapsecns.vercel.app)

Fixes decimals

---

.github/workflows/solidity.yml
.gitignore

vercel workflow fix

---

.github/workflows/solidity.yml

fix prod deploy

---

packages/synapse-interface/components/Warning.tsx

null
c1411691f5a9d7ef8e29b2ba696705a37db7f441: [synapse-interface preview link ](https://sanguine-synapse-interface-aewr62gkd-synapsecns.vercel.app)
e122746a35752d50ce98179b1a907e1732beb869: [synapse-interface preview link ](https://sanguine-synapse-interface-hkxnlmn83-synapsecns.vercel.app)

Checks if route is CCTP before presenting note

---

.github/workflows/changesets.yml
.github/workflows/clean-up-pr-caches.yml
.github/workflows/codeql.yaml
.github/workflows/cypress.yml
.github/workflows/devcontainer.yml
.github/workflows/fail-on-needs-generate.yaml
.github/workflows/foundry-tests.yml
.github/workflows/go.yml
.github/workflows/goreleaser-actions.yml
.github/workflows/helm-release.yml
.github/workflows/helm-test.yml
.github/workflows/jaeger-ui.yml
.github/workflows/label-requires-reviews.yml
.github/workflows/label-statuses.yml
.github/workflows/lerna.yaml
.github/workflows/lint.yml
.github/workflows/packages.yml
.github/workflows/solidity.yml
.github/workflows/sonar.yml
.github/workflows/ui-preview.yaml

upgrade actions (required for synapsecns/sanguine#1339)

---

packages/contracts-core/package.json

Publish contracts core npm package

publish contracts package

---

packages/contracts-core/package.json

Contract Version Bump

---

.github/workflows/lerna.yaml
packages/contracts-core/package.json

Make Contracts installable for Docs

---

packages/contracts-core/README.md

interchain docs

---

packages/synapse-interface/components/Banner.tsx

Switch to more detailed tweet link

switch to more detailed tweet link

---

packages/synapse-interface/pages/pool/PoolBody.tsx
packages/synapse-interface/utils/actions/approveAndDeposit.tsx
packages/synapse-interface/utils/actions/approveAndWithdraw.tsx

null
2fec08a73bdf1bf9693ccf15e4343f5dc26be4f6: [synapse-interface preview link ](https://sanguine-synapse-interface-ecxijs6mm-synapsecns.vercel.app)

Moves title info to metadata

---

packages/synapse-interface/package.json
packages/synapse-interface/pages/index.tsx
yarn.lock

instrument fe to determine explorer load

---

packages/synapse-interface/graphql/GetUserHistoricalTransactions.graphql
packages/synapse-interface/graphql/GetUserPendingTransactions.graphql
packages/synapse-interface/slices/api/generated.ts
packages/synapse-interface/slices/transactions/updater.tsx

update gql useMv to true

---

packages/explorer-ui/package.json
packages/explorer-ui/pages/index.tsx

Add instruments for #1363 hotfixes

instrumentation for #1363

---

packages/synapse-interface/package.json
packages/synapse-interface/pages/_app.tsx
yarn.lock

add vercel instrumentation

---

.github/workflows/go.yml
.github/workflows/goreleaser-actions.yml

Reverts to latest since #1399 is merged

Use Latest Git-Changes Action

---

.github/workflows/clean-up-pr.yml
.github/workflows/go.yml

Don't run github.ref on master

don't run on master

---

.github/workflows/clean-up-pr.yml
.github/workflows/go.yml

softfail cleanup

---

packages/contracts-core/package.json
yarn.lock

This PR resolves ToB-19 by updating OZ packages to their latest 4.9.x version.

Fix: ToB-19 update dependencies

---

contrib/promexporter/internal/gql/dfk/client.gen.go
contrib/promexporter/internal/gql/dfk/models.gen.go

Updates prometheues exporter w/ new fetched gql schemas

updates prom exporter

---

yarn.lock

yarn install (Fixes go generate issues in #1492

---

CONTRIBUTING.md

Remove invalid option from contributing.md .goreleaser spec (This was removed in [goreleaser 1.19](https://carlosbecker.com/posts/goreleaser-v1.19) (goreleaser/goreleaser#4076)

remove archives from contributing

---

packages/synapse-interface/cypress/fixtures/navigation.json

null
63e7e2a737d5d5856964e841bff4d8852b8fd285: [synapse-interface preview link ](https://sanguine-synapse-interface-aorft2uxb-synapsecns.vercel.app)

Update cypress integration tests for new route

---

packages/sdk-router/jest.config.js

Limit concurrency in the SDK tests

---

.github/workflows/packages.yml
.gitignore
packages/sdk-router/.env.example
packages/sdk-router/package.json
packages/sdk-router/src/constants/testValues.ts
packages/sdk-router/src/router/synapseCCTPRouter.test.ts
packages/sdk-router/src/router/synapseCCTPRouterSet.test.ts
packages/sdk-router/src/router/synapseRouter.test.ts
packages/sdk-router/src/router/synapseRouterSet.test.ts
packages/sdk-router/src/sdk.test.ts
yarn.lock

Fixes flaky SDK tests by using more reliable RPC nodes.

Sdk: fix flaky tests

---

.github/labeler.yml
packages/synapse-interface/components/StateManagedBridge/ToTokenListOverlay.tsx
packages/synapse-interface/components/StateManagedBridge/components/SelectSpecificTokenButton.tsx
yarn.lock

Update Destination Token List to use fetched bridge quote `estimatedTime` value
28c420afcc923cf4bb3c2dda21da6fb7b62a7b55: [synapse-interface preview link ](https://sanguine-synapse-interface-4uk6hfhmm-synapsecns.vercel.app)
31d1a3617ab0cfe8f556621d8b7f9f1c45397fc6: [synapse-interface preview link ](https://sanguine-synapse-interface-86scdsiyn-synapsecns.vercel.app)
e50862544fdabd50e598d215689daa7b43750bcd: [synapse-interface preview link ](https://sanguine-synapse-interface-6ws54o54d-synapsecns.vercel.app)
338bf1ab3fdbadcf36cc9ce75c22244986212fab: [synapse-interface preview link ](https://sanguine-synapse-interface-n9um5phv1-synapsecns.vercel.app)
3aedeed27f9d40dfd5cc02b7b0416a5307a9b7db: [synapse-interface preview link ](https://sanguine-synapse-interface-23muix2ue-synapsecns.vercel.app) …

Update Token List to use estimatedBridgeTime from SDK

---

CONTRIBUTING.md

bump version in CONTRIBUTING.md

---

ethergo/signer/signer/localsigner/signer.go
ethergo/signer/signer/signer.go

remove eip-155 considerations from arbitrary data signing (#1634)

---

ethergo/signer/signer/localsigner/signer.go
ethergo/signer/signer/signer.go

Reverts synapsecns/sanguine#1661

Revert "remove eip-155 considerations from arbitrary data signing (#1634)"

---

packages/synapse-interface/package.json

upgrade wagmi/core

---

packages/synapse-interface/components/StateManagedBridge/BridgeTransactionButton.tsx
packages/synapse-interface/constants/chains/index.tsx

null
546cf7cf6cfcf4a1f3c9627f26de0311876bd745: [synapse-interface preview link ](https://sanguine-synapse-interface-ekmi3gx6w-synapsecns.vercel.app)

Hides Harmony

---

packages/synapse-interface/cypress/fixtures/bridge.json

null
7d338540b1d9eb7cb5731bd6ca5a21231586a238: [synapse-interface preview link ](https://sanguine-synapse-interface-5j2uallsg-synapsecns.vercel.app)

Temp remove Harmony from integration tests

---

packages/sdk-router/src/rfq/api.test.ts
packages/sdk-router/src/rfq/fastBridgeSet.test.ts
packages/sdk-router/src/rfq/quote.test.ts
packages/sdk-router/src/rfq/quote.ts

Use snake case for quote API

---

services/rfq/relayer/service/handlers.go

[rfq] should process is completely ignored

---

.github/workflows/go.yml
services/rfq/README.md

Always run on default branch to fix codecov

always run on default branch

---

contrib/promexporter/config/config.go

update promexporter to track rfq address

---

packages/sdk-router/src/constants/chainIds.ts

add eth to router

---

packages/sdk-router/src/rfq/fastBridgeSet.ts

fix getQuotes toLowercase typeError

---

packages/synapse-interface/slices/_transactions/reducer.ts

check if state.transactions exists

---

services/rfq/relayer/pricer/fee_pricer.go

Fix span leak introduced in #1799

fix other span leak

---

packages/sdk-router/src/constants/medianTime.ts

add sdk rfq estimated time

---

packages/synapse-interface/CHANGELOG.md
packages/synapse-interface/components/Portfolio/PortfolioContent/components/PortfolioTokenAsset.tsx
packages/synapse-interface/components/StateManagedBridge/ToTokenListOverlay.tsx
packages/synapse-interface/constants/chains/master.tsx
packages/synapse-interface/package.json
packages/synapse-interface/pages/state-managed-bridge/index.tsx
packages/synapse-interface/pages/swap/index.tsx
packages/synapse-interface/slices/bridge/updater.tsx
packages/synapse-interface/slices/transactions/updater.tsx
packages/synapse-interface/utils/actions/fetchBridgeQuotes.tsx
packages/synapse-interface/utils/hooks/useAlternateBridgeQuotes.ts
packages/synapse-interface/utils/isEmptyString.ts
packages/synapse-interface/utils/providers/SynapseProvider.tsx
packages/synapse-interface/utils/regex.tsx
services/rfq/relayer/relconfig/config.go
services/rfq/relayer/relconfig/iconfig_generated.go
services/rfq/relayer/service/statushandler.go

**Metadata**
78495be8a2111d16425ca1ee50efede4e96ce0f9: [synapse-interface preview link ](https://sanguine-synapse-interface-qpg8zzx3c-synapsecns.vercel.app)

Release 2024 01 18

---

packages/synapse-interface/components/Portfolio/PortfolioTabManager.tsx

null
74425358d9db549687dfda1365c3cee4f04005d8: [synapse-interface preview link ](https://sanguine-synapse-interface-7t9hdipq5-synapsecns.vercel.app)

Hide txns if not connected

---

charts/screener/Chart.yaml
charts/screener/templates/service.yaml

[screener] fix helm chart

---

packages/sdk-router/src/constants/medianTime.ts

update rfq median times to follow dune query

---

services/explorer/graphql/server/graph/queries.resolvers.go

fix explorer error message

---

.github/workflows/goreleaser-actions.yml
core/README.md

autorefresh report card

---

core/README.md
docker/goreleaser/Dockerfile

install jq (fixes #1949)

---

.github/workflows/goreleaser-actions.yml
contrib/git-changes-action/README.md

fix dir bug

---

packages/widget/package.json

Update package.json (#1974)

---

packages/widget/src/components/ui/ChainPopoverSelect.tsx
packages/widget/src/components/ui/TokenPopoverSelect.tsx
packages/widget/tailwind.config.js

popover side-down transition

---

packages/sdk-router/src/sdk.test.ts

Upd SDK test: receive USDC via SynapseBridge on AVAX

---

.codeclimate.yml

ignore globs

---

packages/contracts-communication/contracts/libs/ThresholdECDSA.sol
packages/contracts-communication/test/harnesses/ThresholdECDSALibHarness.sol
packages/contracts-communication/test/libs/ThresholdECDSALib.t.sol

Solidity library for generic M/N signature verification

---

packages/synapse-interface/components/Activity/Activity.tsx
packages/synapse-interface/components/Portfolio/Portfolio.tsx

Relocating `Activity.tsx` to `/components/activity` folder, was previously located in `components/portfolio` prior to refactor
449a44e10ee2a259d1c0849c1cfff8983977a0da: [synapse-interface preview link ](https://sanguine-synapse-interface-gd99fhrkf-synapsecns.vercel.app)

move Activity to component folder

---

packages/contracts-communication/contracts/InterchainClientV1.sol
packages/contracts-communication/contracts/interfaces/IInterchainApp.sol
packages/contracts-communication/contracts/interfaces/IInterchainClientV1.sol
packages/contracts-communication/test/InterchainClientV1Test.t.sol
packages/contracts-communication/test/mocks/InterchainAppMock.sol

Implements message passing to the app.

Feat: message passing

---

services/rfq/go.mod

adds mod directive

---

packages/solidity-devops/package.json

add publish bc of public

---

contrib/promexporter/internal/gql/dfk/models.gen.go

Regen promexporter

---

packages/synapse-interface/components/Pools/PoolCardBody.tsx
packages/synapse-interface/pages/stake/StakeCardTitle.tsx

update pool info

---

packages/synapse-interface/CHANGELOG.md
packages/synapse-interface/components/Pools/PoolCardBody.tsx
packages/synapse-interface/package.json
packages/synapse-interface/pages/stake/StakeCardTitle.tsx
packages/widget/CHANGELOG.md
packages/widget/package.json
packages/widget/src/constants/bridgeMap.ts
packages/widget/src/constants/bridgeable.ts
packages/widget/src/constants/chains.ts

**Metadata**
b3d84e24603a151bf12ee13a0e8f802ce7e77045: [synapse-interface preview link ](https://sanguine-synapse-interface-5iu03gtqf-synapsecns.vercel.app)

release 03-01

---

sin-executor/config/config.go
sin-executor/executor/executor.go
sin-executor/executor/suite_test.go

SIN Executor Config Chain ID restructure

---

packages/synapse-interface/components/StateManagedBridge/BridgeExchangeRateInfo.tsx

clean up bridge card component

---

packages/synapse-interface/CHANGELOG.md
packages/synapse-interface/components/StateManagedBridge/BridgeExchangeRateInfo.tsx
packages/synapse-interface/package.json

Release 3-6 2

---

.github/workflows/solidity.yml
packages/contracts-interchain/vercel.package.json

add doc generation to interchain contracts

interchain contract docs

---

.coderabbit.yaml

Instruct coderabbit not to review generated files

coderabbit cleanup

---

CONTRIBUTING.md

fix contributing.md spacing

---

services/stiprelayer/go.mod

nit: remove extraneous directives from stiprelayer

---

packages/synapse-interface/components/Maintenance/Events/MetisUpgrade.tsx

extend metis

---

sin-executor/executor/suite_test.go
sin-executor/testutil/deployers.go

backup pre-aurelius

---

.coderabbit.yaml

Very annoying, see [here](https://github.com/synapsecns/sanguine/pull/2234#discussion_r1533719763)

instruct coderabbit not to rc

---

.github/workflows/go.yml
.github/workflows/goreleaser-actions.yml
.github/workflows/scan.yml

fix contributor workflow (for #2355). Replaces #2357 which as made against an ancient version of master

fix go workflow

---

.github/workflows/go.yml
.github/workflows/goreleaser-actions.yml

chore(git-changes-action): stage git changes action

---

packages/sdk-router/src/constants/chainIds.ts

feat(sdk-router): Add Base to the list of supported RFQ chains

---

ethergo/submitter/db/txdb/store.go

mark all replacedorconfirmed

---

.github/workflows/go.yml
core/README.md

Experiment w/ more shallow clones on goreleaser
As mentioned this may end up being slower: https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935

don't clone submodules for change detection

---

.github/workflows/go.yml
.github/workflows/goreleaser-actions.yml

stage #2355

---

contrib/promexporter/README.md

chore: fix typo in promexporter readme

---

packages/synapse-interface/pages/returntomonke/ImageUploader.tsx

null
3779eba49bde50324fdb4e03bd5b1712c665c5cf: [synapse-interface preview link ](https://sanguine-synapse-interface-iud98whv9-synapsecns.vercel.app)
b29832a4d709ba24c1f21362e361a6d387eda39c: [synapse-interface preview link ](https://sanguine-synapse-interface-kf2gpb9ky-synapsecns.vercel.app)

Format exported synape PFP

---

contrib/screener-api/README.md

screener api

---

.github/workflows/close-stale.yml

Exempt pages from workflow runs

Exempt gh pages

---

packages/coverage-aggregator/package.json

make coverage aggregator public

---

.github/workflows/ui-preview.yaml
docs/bridge/README.md

fix(ci): fixes bug in #2627, deploys go to prod

---

CONTRIBUTING.md

revert coderabbit fix

---

ethergo/listener/listener.go

Make poll interval easy to set

optional settable poll interval

---

ethergo/listener/listener.go

poll interval increase

---

ethergo/listener/listener.go
ethergo/listener/listener_test.go
ethergo/listener/options.go

Adds a hook to the listener to allow blocks to be logged

add hook to listener

---

docs/bridge/package.json

fix slither

---

core/README.md
docker/goreleaser/Dockerfile

replaces #2729 
shaves 10 seconds off goreleaser time

smaller image

---

.github/workflows/goreleaser-actions.yml
core/README.md

speeds pu goreleaser w caching

speed up goreleaser with caching

---

contrib/opbot/README.md

add opbot badges to readme

---

packages/synapse-interface/public/pauses/v1/paused-chains.json

Unpauses blast
13b2c7940dddb382dcba943d9171a76f0d2f40c0: [synapse-interface preview link ](https://sanguine-synapse-interface-f69sv9lij-synapsecns.vercel.app)

Unpauses blast

---

.codeclimate.yml

codeclimate fixes

---

docs/bridge/docs/Services/Signer.md

Cleanup
b45a6e1902f3a97326a66c3ed7f4f427cfc45f08: [docs preview link ](https://bridge-docs-hnmvhyqht-synapsecns.vercel.app)

format string literals in signer docs

---

core/bytes_test.go

Fix lint issue introduced in #2802

fix: core lint

---

packages/synapse-interface/CHANGELOG.md
packages/synapse-interface/README.md
packages/synapse-interface/constants/chains/master.tsx
packages/synapse-interface/package.json

null
c15c6c492fef82aa98c351833a7e2f72a893c4ca: [synapse-interface preview link ](https://sanguine-synapse-interface-nffjxj23v-synapsecns.vercel.app)

FE Release 2024-07-17 #2

---

contrib/promexporter/internal/gql/dfk/models.gen.go

model was out of date
(fix for #2933)

update dfk model

---

docs/bridge/docs/rfq/Contracts.md

Updates the contracts for new chains

Updating rfq contracts in docs

---

packages/synapse-interface/components/ui/AmountInput.tsx
packages/synapse-interface/package.json
yarn.lock

null
b2c637f9f66dc6e195232aad854c893000684eaf: [synapse-interface preview link ](https://sanguine-synapse-interface-g205pe6hh-synapsecns.vercel.app)
8f81c40576391ead0ff85522cd62d6790698c622: [synapse-interface preview link ](https://sanguine-synapse-interface-hco7vkt4l-synapsecns.vercel.app)
d1981540b2dc3bcb04b36aab4f15aa9e4c6f95a3: [synapse-interface preview link ](https://sanguine-synapse-interface-arjsv0sa5-synapsecns.vercel.app)

feat(synapse-interface): numerical input format

---

packages/synapse-interface/components/StateManagedBridge/OutputContainer.tsx
packages/synapse-interface/pages/state-managed-bridge/index.tsx
packages/synapse-interface/utils/hooks/useStaleQuoteUpdater.ts

null
ef6d41ca1fe60d3b633a1f0a02b835921c0471aa: [synapse-interface preview link ](https://sanguine-synapse-interface-417lhnm39-synapsecns.vercel.app)
69bde354a26be85a33ce4f1f02910ab5ce262b11: [synapse-interface preview link ](https://sanguine-synapse-interface-atdjjrz2k-synapsecns.vercel.app)

[WIP] stale quote animation

---

packages/synapse-interface/messages/ar.json

Updates the arabic
13aded2838aeddc28226743c7dee52ba54d5c14b: [synapse-interface preview link ](https://sanguine-synapse-interface-1xte5ke6q-synapsecns.vercel.app)

Updating Arabic translation

---

docs/bridge/docs/Routers/RFQ/index.md
docs/bridge/docusaurus.config.ts
docs/bridge/package.json
yarn.lock

null
478883cbb3fcb791d5fbd6121d25e8647ef8016b: [docs preview link ](https://bridge-docs-jakky517c-synapsecns.vercel.app)

Fixes build issue

---

packages/rfq-indexer/api/README.md

Areas of the docs we are updating: 
- RFQ Indexer API readme
- RFQ Indexer API in the newly updated user facing docs
- Various terminology in the contracts section of the user facing docs.

Updating docs

---

contrib/promexporter/internal/gql/dfk/models.gen.go

regenerate prom exporter

---

docs/bridge/docusaurus.config.ts

 move docs [SLT-133]

---

docs/bridge/docusaurus.config.ts

**Metadata**
a40bba504b42a1ef30c77361e065dbf1404e5d89: [docs preview link ](https://bridge-docs-egphyo2qn-synapsecns.vercel.app)
6ce58993d1deb42cac92e74aa88db4d28e847d6a: [docs preview link ](https://bridge-docs-2qy6xll4d-synapsecns.vercel.app)

Fix/edit url [SLT-338]

---

packages/contracts-rfq/package.json

fix(contracts-rfq): skip version to unbrick lerna

---

docs/bridge/docusaurus.config.ts

fix the direct link
590bf0dada4dea8c34fd2359ffdfcfc847d538d4: [docs preview link ](https://bridge-docs-9hpb8409y-synapsecns.vercel.app)

docs: fix direct link

---

packages/contracts-rfq/foundry.toml

build(contracts-rfq): increase optimizer runs to 1M [SLT-294]

---

packages/rest-api/package.json

bump ts version

---

packages/synapse-interface/CHANGELOG.md
packages/synapse-interface/components/layouts/LandingPageWrapper/index.tsx
packages/synapse-interface/constants/routes.ts
packages/synapse-interface/constants/urls/index.tsx
packages/synapse-interface/messages/ar.json
packages/synapse-interface/messages/en-US.json
packages/synapse-interface/messages/es.json
packages/synapse-interface/messages/fr.json
packages/synapse-interface/messages/jp.json
packages/synapse-interface/messages/tr.json
packages/synapse-interface/messages/zh-CN.json
packages/synapse-interface/package.json

null
fdbe4297eee8d67946906f090c1b17713e930133: [synapse-interface preview link ](https://sanguine-synapse-interface-du7xyqejt-synapsecns.vercel.app)

FE Release 2024-12-30

---

packages/rest-api/src/routes/addressIconRoute.ts

fix missing lint for #3505

---

packages/rest-api/README.md
packages/rest-api/src/utils/isGatewayRoute.ts
packages/sdk-router/README.md
packages/sdk-router/src/rfq/api.ts

chore: add overridable for api urls

---

packages/synapse-constants/README.md
yarn.lock

fix: yarn lock file

---

packages/sdk-router/README.md

chore: small change to trigger publish workflows

---

packages/synapse-interface/public/pauses/v1/paused-chains.json

fix(synapse-interface): unpause Klaytn chain

---

services/rfq/relayer/quoter/quoter.go
services/rfq/relayer/quoter/quoter_test.go

fix: apply `MaxRelayAmount` on origin for quotes

---

packages/sdk-router/README.md

chore: small change to publish 9abecbef5ff8e07c969832c3eb357ca3cf06d20a

---

docs/bridge/src/components/Routes.tsx

Updating Supported Token Lists
